// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type WateringInput struct {
	Channel string `json:"channel"`
	Seconds int32  `json:"seconds"`
}
