// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// WaterLogsColumns holds the columns for the "water_logs" table.
	WaterLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "seconds", Type: field.TypeInt32},
		{Name: "channel", Type: field.TypeString},
		{Name: "manual", Type: field.TypeBool},
		{Name: "time", Type: field.TypeTime},
	}
	// WaterLogsTable holds the schema information for the "water_logs" table.
	WaterLogsTable = &schema.Table{
		Name:       "water_logs",
		Columns:    WaterLogsColumns,
		PrimaryKey: []*schema.Column{WaterLogsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		WaterLogsTable,
	}
)

func init() {
}
