// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"plant-watering/ent/waterlog"

	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Common entgql types.
type (
	Cursor         = entgql.Cursor[uuid.UUID]
	PageInfo       = entgql.PageInfo[uuid.UUID]
	OrderDirection = entgql.OrderDirection
)

func orderFunc(o OrderDirection, field string) func(*sql.Selector) {
	if o == entgql.OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// WaterLogEdge is the edge representation of WaterLog.
type WaterLogEdge struct {
	Node   *WaterLog `json:"node"`
	Cursor Cursor    `json:"cursor"`
}

// WaterLogConnection is the connection containing edges to WaterLog.
type WaterLogConnection struct {
	Edges      []*WaterLogEdge `json:"edges"`
	PageInfo   PageInfo        `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

func (c *WaterLogConnection) build(nodes []*WaterLog, pager *waterlogPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *WaterLog
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *WaterLog {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *WaterLog {
			return nodes[i]
		}
	}
	c.Edges = make([]*WaterLogEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &WaterLogEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// WaterLogPaginateOption enables pagination customization.
type WaterLogPaginateOption func(*waterlogPager) error

// WithWaterLogOrder configures pagination ordering.
func WithWaterLogOrder(order *WaterLogOrder) WaterLogPaginateOption {
	if order == nil {
		order = DefaultWaterLogOrder
	}
	o := *order
	return func(pager *waterlogPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultWaterLogOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithWaterLogFilter configures pagination filter.
func WithWaterLogFilter(filter func(*WaterLogQuery) (*WaterLogQuery, error)) WaterLogPaginateOption {
	return func(pager *waterlogPager) error {
		if filter == nil {
			return errors.New("WaterLogQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type waterlogPager struct {
	reverse bool
	order   *WaterLogOrder
	filter  func(*WaterLogQuery) (*WaterLogQuery, error)
}

func newWaterLogPager(opts []WaterLogPaginateOption, reverse bool) (*waterlogPager, error) {
	pager := &waterlogPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultWaterLogOrder
	}
	return pager, nil
}

func (p *waterlogPager) applyFilter(query *WaterLogQuery) (*WaterLogQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *waterlogPager) toCursor(wl *WaterLog) Cursor {
	return p.order.Field.toCursor(wl)
}

func (p *waterlogPager) applyCursors(query *WaterLogQuery, after, before *Cursor) (*WaterLogQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultWaterLogOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *waterlogPager) applyOrder(query *WaterLogQuery) *WaterLogQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultWaterLogOrder.Field {
		query = query.Order(DefaultWaterLogOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *waterlogPager) orderExpr(query *WaterLogQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultWaterLogOrder.Field {
			b.Comma().Ident(DefaultWaterLogOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to WaterLog.
func (wl *WaterLogQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...WaterLogPaginateOption,
) (*WaterLogConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newWaterLogPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if wl, err = pager.applyFilter(wl); err != nil {
		return nil, err
	}
	conn := &WaterLogConnection{Edges: []*WaterLogEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := wl.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if wl, err = pager.applyCursors(wl, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		wl.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := wl.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	wl = pager.applyOrder(wl)
	nodes, err := wl.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// WaterLogOrderField defines the ordering field of WaterLog.
type WaterLogOrderField struct {
	// Value extracts the ordering value from the given WaterLog.
	Value    func(*WaterLog) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) waterlog.OrderOption
	toCursor func(*WaterLog) Cursor
}

// WaterLogOrder defines the ordering of WaterLog.
type WaterLogOrder struct {
	Direction OrderDirection      `json:"direction"`
	Field     *WaterLogOrderField `json:"field"`
}

// DefaultWaterLogOrder is the default ordering of WaterLog.
var DefaultWaterLogOrder = &WaterLogOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &WaterLogOrderField{
		Value: func(wl *WaterLog) (ent.Value, error) {
			return wl.ID, nil
		},
		column: waterlog.FieldID,
		toTerm: waterlog.ByID,
		toCursor: func(wl *WaterLog) Cursor {
			return Cursor{ID: wl.ID}
		},
	},
}

// ToEdge converts WaterLog into WaterLogEdge.
func (wl *WaterLog) ToEdge(order *WaterLogOrder) *WaterLogEdge {
	if order == nil {
		order = DefaultWaterLogOrder
	}
	return &WaterLogEdge{
		Node:   wl,
		Cursor: order.Field.toCursor(wl),
	}
}
