// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"plant-watering/ent/predicate"
	"plant-watering/ent/waterlog"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeWaterLog = "WaterLog"
)

// WaterLogMutation represents an operation that mutates the WaterLog nodes in the graph.
type WaterLogMutation struct {
	config
	op            Op
	typ           string
	id            *int
	seconds       *int
	addseconds    *int
	channel       *string
	manual        *bool
	time          *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*WaterLog, error)
	predicates    []predicate.WaterLog
}

var _ ent.Mutation = (*WaterLogMutation)(nil)

// waterlogOption allows management of the mutation configuration using functional options.
type waterlogOption func(*WaterLogMutation)

// newWaterLogMutation creates new mutation for the WaterLog entity.
func newWaterLogMutation(c config, op Op, opts ...waterlogOption) *WaterLogMutation {
	m := &WaterLogMutation{
		config:        c,
		op:            op,
		typ:           TypeWaterLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withWaterLogID sets the ID field of the mutation.
func withWaterLogID(id int) waterlogOption {
	return func(m *WaterLogMutation) {
		var (
			err   error
			once  sync.Once
			value *WaterLog
		)
		m.oldValue = func(ctx context.Context) (*WaterLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().WaterLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withWaterLog sets the old WaterLog of the mutation.
func withWaterLog(node *WaterLog) waterlogOption {
	return func(m *WaterLogMutation) {
		m.oldValue = func(context.Context) (*WaterLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m WaterLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m WaterLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *WaterLogMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *WaterLogMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().WaterLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSeconds sets the "seconds" field.
func (m *WaterLogMutation) SetSeconds(i int) {
	m.seconds = &i
	m.addseconds = nil
}

// Seconds returns the value of the "seconds" field in the mutation.
func (m *WaterLogMutation) Seconds() (r int, exists bool) {
	v := m.seconds
	if v == nil {
		return
	}
	return *v, true
}

// OldSeconds returns the old "seconds" field's value of the WaterLog entity.
// If the WaterLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WaterLogMutation) OldSeconds(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSeconds is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSeconds requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSeconds: %w", err)
	}
	return oldValue.Seconds, nil
}

// AddSeconds adds i to the "seconds" field.
func (m *WaterLogMutation) AddSeconds(i int) {
	if m.addseconds != nil {
		*m.addseconds += i
	} else {
		m.addseconds = &i
	}
}

// AddedSeconds returns the value that was added to the "seconds" field in this mutation.
func (m *WaterLogMutation) AddedSeconds() (r int, exists bool) {
	v := m.addseconds
	if v == nil {
		return
	}
	return *v, true
}

// ResetSeconds resets all changes to the "seconds" field.
func (m *WaterLogMutation) ResetSeconds() {
	m.seconds = nil
	m.addseconds = nil
}

// SetChannel sets the "channel" field.
func (m *WaterLogMutation) SetChannel(s string) {
	m.channel = &s
}

// Channel returns the value of the "channel" field in the mutation.
func (m *WaterLogMutation) Channel() (r string, exists bool) {
	v := m.channel
	if v == nil {
		return
	}
	return *v, true
}

// OldChannel returns the old "channel" field's value of the WaterLog entity.
// If the WaterLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WaterLogMutation) OldChannel(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldChannel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldChannel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldChannel: %w", err)
	}
	return oldValue.Channel, nil
}

// ResetChannel resets all changes to the "channel" field.
func (m *WaterLogMutation) ResetChannel() {
	m.channel = nil
}

// SetManual sets the "manual" field.
func (m *WaterLogMutation) SetManual(b bool) {
	m.manual = &b
}

// Manual returns the value of the "manual" field in the mutation.
func (m *WaterLogMutation) Manual() (r bool, exists bool) {
	v := m.manual
	if v == nil {
		return
	}
	return *v, true
}

// OldManual returns the old "manual" field's value of the WaterLog entity.
// If the WaterLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WaterLogMutation) OldManual(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldManual is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldManual requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldManual: %w", err)
	}
	return oldValue.Manual, nil
}

// ResetManual resets all changes to the "manual" field.
func (m *WaterLogMutation) ResetManual() {
	m.manual = nil
}

// SetTime sets the "time" field.
func (m *WaterLogMutation) SetTime(t time.Time) {
	m.time = &t
}

// Time returns the value of the "time" field in the mutation.
func (m *WaterLogMutation) Time() (r time.Time, exists bool) {
	v := m.time
	if v == nil {
		return
	}
	return *v, true
}

// OldTime returns the old "time" field's value of the WaterLog entity.
// If the WaterLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WaterLogMutation) OldTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTime: %w", err)
	}
	return oldValue.Time, nil
}

// ResetTime resets all changes to the "time" field.
func (m *WaterLogMutation) ResetTime() {
	m.time = nil
}

// Where appends a list predicates to the WaterLogMutation builder.
func (m *WaterLogMutation) Where(ps ...predicate.WaterLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the WaterLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *WaterLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.WaterLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *WaterLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *WaterLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (WaterLog).
func (m *WaterLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *WaterLogMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.seconds != nil {
		fields = append(fields, waterlog.FieldSeconds)
	}
	if m.channel != nil {
		fields = append(fields, waterlog.FieldChannel)
	}
	if m.manual != nil {
		fields = append(fields, waterlog.FieldManual)
	}
	if m.time != nil {
		fields = append(fields, waterlog.FieldTime)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *WaterLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case waterlog.FieldSeconds:
		return m.Seconds()
	case waterlog.FieldChannel:
		return m.Channel()
	case waterlog.FieldManual:
		return m.Manual()
	case waterlog.FieldTime:
		return m.Time()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *WaterLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case waterlog.FieldSeconds:
		return m.OldSeconds(ctx)
	case waterlog.FieldChannel:
		return m.OldChannel(ctx)
	case waterlog.FieldManual:
		return m.OldManual(ctx)
	case waterlog.FieldTime:
		return m.OldTime(ctx)
	}
	return nil, fmt.Errorf("unknown WaterLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *WaterLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case waterlog.FieldSeconds:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSeconds(v)
		return nil
	case waterlog.FieldChannel:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetChannel(v)
		return nil
	case waterlog.FieldManual:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetManual(v)
		return nil
	case waterlog.FieldTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTime(v)
		return nil
	}
	return fmt.Errorf("unknown WaterLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *WaterLogMutation) AddedFields() []string {
	var fields []string
	if m.addseconds != nil {
		fields = append(fields, waterlog.FieldSeconds)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *WaterLogMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case waterlog.FieldSeconds:
		return m.AddedSeconds()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *WaterLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	case waterlog.FieldSeconds:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSeconds(v)
		return nil
	}
	return fmt.Errorf("unknown WaterLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *WaterLogMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *WaterLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *WaterLogMutation) ClearField(name string) error {
	return fmt.Errorf("unknown WaterLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *WaterLogMutation) ResetField(name string) error {
	switch name {
	case waterlog.FieldSeconds:
		m.ResetSeconds()
		return nil
	case waterlog.FieldChannel:
		m.ResetChannel()
		return nil
	case waterlog.FieldManual:
		m.ResetManual()
		return nil
	case waterlog.FieldTime:
		m.ResetTime()
		return nil
	}
	return fmt.Errorf("unknown WaterLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *WaterLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *WaterLogMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *WaterLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *WaterLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *WaterLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *WaterLogMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *WaterLogMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown WaterLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *WaterLogMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown WaterLog edge %s", name)
}
