// Code generated by ent, DO NOT EDIT.

package ent

import (
	"plant-watering/ent/schema"
	"plant-watering/ent/waterlog"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	waterlogFields := schema.WaterLog{}.Fields()
	_ = waterlogFields
	// waterlogDescTime is the schema descriptor for time field.
	waterlogDescTime := waterlogFields[3].Descriptor()
	// waterlog.DefaultTime holds the default value on creation for the time field.
	waterlog.DefaultTime = waterlogDescTime.Default.(func() time.Time)
}
