// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"plant-watering/ent/predicate"
	"plant-watering/ent/waterlog"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WaterLogQuery is the builder for querying WaterLog entities.
type WaterLogQuery struct {
	config
	ctx        *QueryContext
	order      []waterlog.OrderOption
	inters     []Interceptor
	predicates []predicate.WaterLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WaterLogQuery builder.
func (wlq *WaterLogQuery) Where(ps ...predicate.WaterLog) *WaterLogQuery {
	wlq.predicates = append(wlq.predicates, ps...)
	return wlq
}

// Limit the number of records to be returned by this query.
func (wlq *WaterLogQuery) Limit(limit int) *WaterLogQuery {
	wlq.ctx.Limit = &limit
	return wlq
}

// Offset to start from.
func (wlq *WaterLogQuery) Offset(offset int) *WaterLogQuery {
	wlq.ctx.Offset = &offset
	return wlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wlq *WaterLogQuery) Unique(unique bool) *WaterLogQuery {
	wlq.ctx.Unique = &unique
	return wlq
}

// Order specifies how the records should be ordered.
func (wlq *WaterLogQuery) Order(o ...waterlog.OrderOption) *WaterLogQuery {
	wlq.order = append(wlq.order, o...)
	return wlq
}

// First returns the first WaterLog entity from the query.
// Returns a *NotFoundError when no WaterLog was found.
func (wlq *WaterLogQuery) First(ctx context.Context) (*WaterLog, error) {
	nodes, err := wlq.Limit(1).All(setContextOp(ctx, wlq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{waterlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wlq *WaterLogQuery) FirstX(ctx context.Context) *WaterLog {
	node, err := wlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WaterLog ID from the query.
// Returns a *NotFoundError when no WaterLog ID was found.
func (wlq *WaterLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wlq.Limit(1).IDs(setContextOp(ctx, wlq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{waterlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wlq *WaterLogQuery) FirstIDX(ctx context.Context) int {
	id, err := wlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WaterLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WaterLog entity is found.
// Returns a *NotFoundError when no WaterLog entities are found.
func (wlq *WaterLogQuery) Only(ctx context.Context) (*WaterLog, error) {
	nodes, err := wlq.Limit(2).All(setContextOp(ctx, wlq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{waterlog.Label}
	default:
		return nil, &NotSingularError{waterlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wlq *WaterLogQuery) OnlyX(ctx context.Context) *WaterLog {
	node, err := wlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WaterLog ID in the query.
// Returns a *NotSingularError when more than one WaterLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (wlq *WaterLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wlq.Limit(2).IDs(setContextOp(ctx, wlq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{waterlog.Label}
	default:
		err = &NotSingularError{waterlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wlq *WaterLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := wlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WaterLogs.
func (wlq *WaterLogQuery) All(ctx context.Context) ([]*WaterLog, error) {
	ctx = setContextOp(ctx, wlq.ctx, "All")
	if err := wlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WaterLog, *WaterLogQuery]()
	return withInterceptors[[]*WaterLog](ctx, wlq, qr, wlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wlq *WaterLogQuery) AllX(ctx context.Context) []*WaterLog {
	nodes, err := wlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WaterLog IDs.
func (wlq *WaterLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if wlq.ctx.Unique == nil && wlq.path != nil {
		wlq.Unique(true)
	}
	ctx = setContextOp(ctx, wlq.ctx, "IDs")
	if err = wlq.Select(waterlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wlq *WaterLogQuery) IDsX(ctx context.Context) []int {
	ids, err := wlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wlq *WaterLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wlq.ctx, "Count")
	if err := wlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wlq, querierCount[*WaterLogQuery](), wlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wlq *WaterLogQuery) CountX(ctx context.Context) int {
	count, err := wlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wlq *WaterLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wlq.ctx, "Exist")
	switch _, err := wlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wlq *WaterLogQuery) ExistX(ctx context.Context) bool {
	exist, err := wlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WaterLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wlq *WaterLogQuery) Clone() *WaterLogQuery {
	if wlq == nil {
		return nil
	}
	return &WaterLogQuery{
		config:     wlq.config,
		ctx:        wlq.ctx.Clone(),
		order:      append([]waterlog.OrderOption{}, wlq.order...),
		inters:     append([]Interceptor{}, wlq.inters...),
		predicates: append([]predicate.WaterLog{}, wlq.predicates...),
		// clone intermediate query.
		sql:  wlq.sql.Clone(),
		path: wlq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Seconds int `json:"seconds,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WaterLog.Query().
//		GroupBy(waterlog.FieldSeconds).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wlq *WaterLogQuery) GroupBy(field string, fields ...string) *WaterLogGroupBy {
	wlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WaterLogGroupBy{build: wlq}
	grbuild.flds = &wlq.ctx.Fields
	grbuild.label = waterlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Seconds int `json:"seconds,omitempty"`
//	}
//
//	client.WaterLog.Query().
//		Select(waterlog.FieldSeconds).
//		Scan(ctx, &v)
func (wlq *WaterLogQuery) Select(fields ...string) *WaterLogSelect {
	wlq.ctx.Fields = append(wlq.ctx.Fields, fields...)
	sbuild := &WaterLogSelect{WaterLogQuery: wlq}
	sbuild.label = waterlog.Label
	sbuild.flds, sbuild.scan = &wlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WaterLogSelect configured with the given aggregations.
func (wlq *WaterLogQuery) Aggregate(fns ...AggregateFunc) *WaterLogSelect {
	return wlq.Select().Aggregate(fns...)
}

func (wlq *WaterLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wlq); err != nil {
				return err
			}
		}
	}
	for _, f := range wlq.ctx.Fields {
		if !waterlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wlq.path != nil {
		prev, err := wlq.path(ctx)
		if err != nil {
			return err
		}
		wlq.sql = prev
	}
	return nil
}

func (wlq *WaterLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WaterLog, error) {
	var (
		nodes = []*WaterLog{}
		_spec = wlq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WaterLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WaterLog{config: wlq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (wlq *WaterLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wlq.querySpec()
	_spec.Node.Columns = wlq.ctx.Fields
	if len(wlq.ctx.Fields) > 0 {
		_spec.Unique = wlq.ctx.Unique != nil && *wlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wlq.driver, _spec)
}

func (wlq *WaterLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(waterlog.Table, waterlog.Columns, sqlgraph.NewFieldSpec(waterlog.FieldID, field.TypeInt))
	_spec.From = wlq.sql
	if unique := wlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wlq.path != nil {
		_spec.Unique = true
	}
	if fields := wlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, waterlog.FieldID)
		for i := range fields {
			if fields[i] != waterlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wlq *WaterLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wlq.driver.Dialect())
	t1 := builder.Table(waterlog.Table)
	columns := wlq.ctx.Fields
	if len(columns) == 0 {
		columns = waterlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wlq.sql != nil {
		selector = wlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wlq.ctx.Unique != nil && *wlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wlq.predicates {
		p(selector)
	}
	for _, p := range wlq.order {
		p(selector)
	}
	if offset := wlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WaterLogGroupBy is the group-by builder for WaterLog entities.
type WaterLogGroupBy struct {
	selector
	build *WaterLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wlgb *WaterLogGroupBy) Aggregate(fns ...AggregateFunc) *WaterLogGroupBy {
	wlgb.fns = append(wlgb.fns, fns...)
	return wlgb
}

// Scan applies the selector query and scans the result into the given value.
func (wlgb *WaterLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wlgb.build.ctx, "GroupBy")
	if err := wlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WaterLogQuery, *WaterLogGroupBy](ctx, wlgb.build, wlgb, wlgb.build.inters, v)
}

func (wlgb *WaterLogGroupBy) sqlScan(ctx context.Context, root *WaterLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wlgb.fns))
	for _, fn := range wlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wlgb.flds)+len(wlgb.fns))
		for _, f := range *wlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WaterLogSelect is the builder for selecting fields of WaterLog entities.
type WaterLogSelect struct {
	*WaterLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wls *WaterLogSelect) Aggregate(fns ...AggregateFunc) *WaterLogSelect {
	wls.fns = append(wls.fns, fns...)
	return wls
}

// Scan applies the selector query and scans the result into the given value.
func (wls *WaterLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wls.ctx, "Select")
	if err := wls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WaterLogQuery, *WaterLogSelect](ctx, wls.WaterLogQuery, wls, wls.inters, v)
}

func (wls *WaterLogSelect) sqlScan(ctx context.Context, root *WaterLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wls.fns))
	for _, fn := range wls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
